<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="robots" content="index, follow">
		<title>Status</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
		<link rel="stylesheet" href="milligram.min.css">
		<link rel="stylesheet" href="style.css">
		
		<link rel="icon" href="https://raw.githubusercontent.com/pyupio/statuspage/master/template/favicon.png">
	</head>
	<body>

		<main class="wrapper">

			<nav class="navigation">
				<section class="container">

					<a class="navigation-title" href="">
						
						<img class="img" src="https://raw.githubusercontent.com/pyupio/statuspage/master/template/logo.png" height="30">
						<h1 class="title">Status</h1>
					</a>



				</section>
			</nav>

			<section class="container" id="main">
				
					
					<div class="panel degraded performance">
						Degraded performance on Anaconda.org, staged-recipes.
					</div>
					
				

				<h4>Systems</h4>
				<ul class="systems">
					
					<li>
						Anaconda.org <span class="status degraded performance">degraded performance</span>
					</li>
					
					<li>
						AppVeyor <span class="status operational">operational</span>
					</li>
					
					<li>
						CircleCI <span class="status operational">operational</span>
					</li>
					
					<li>
						Travis CI <span class="status operational">operational</span>
					</li>
					
					<li>
						conda <span class="status operational">operational</span>
					</li>
					
					<li>
						docs <span class="status operational">operational</span>
					</li>
					
					<li>
						feedstocks <span class="status operational">operational</span>
					</li>
					
					<li>
						linter <span class="status operational">operational</span>
					</li>
					
					<li>
						staged-recipes <span class="status degraded performance">degraded performance</span>
					</li>
					
				</ul>

				<h4>Incidents</h4>
				
					
					<div class="incident">
						<span class="date">2016-09-26 03:43:13 UTC</span>

						
							<span class="label degraded performance float-right">degraded performance</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">AppVeyor API error staged-recipes</span>
						<p><p>Getting HTTP 500 errors from AppVeyor when attempting to create feedstocks. This is blocking conversion.</p>

<p>xref: https://github.com/conda-forge/status/issues/7
xref: https://github.com/conda-forge/status/issues/15</p>
</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-23 00:45:05 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Travis CI OSX maintenance</span>
						<p><p>Travis CI is upgrading OSX infrastructure. All jobs stopped for the next 2hrs. More <a href="https://www.traviscistatus.com/incidents/7yzj0kztkm7q ">info</a>.</p>
</p>
						
							<p><em>Update 2016-09-23 04:01:54</em><br/>
							<p>Maintenance period is complete, but there is a backlog that needs to be processed.</p>

							</p>
						
							<p><em>Update 2016-09-23 16:05:55</em><br/>
							<p>Closing as this appears to have ended and Travis CI builds appear to be running smoothly.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-22 20:46:34 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Degraded Performance Travis CI OS X</span>
						<p><p>Travis CI is <a href="https://www.traviscistatus.com/incidents/68bt45nhq4rf ">reporting</a> degraded performance on OS X builds.</p>
</p>
						
							<p><em>Update 2016-09-23 00:42:32</em><br/>
							<p>Queue returned to normal operating condition.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-21 19:38:10 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Delays on Travis CI's OS X infrastructure</span>
						<p><p>Seeing delays on Travis CI's OS X infrastructure. Please check the <a href="https://www.traviscistatus.com/incidents/v0bxrn0hff5v ">upstream report</a> for details.</p>
</p>
						
							<p><em>Update 2016-09-22 20:44:42</em><br/>
							<p>This particular issue is resolved.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-17 16:53:43 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Anaconda.org</span>
						
						<hr/>

						<span class="title">Problems downloading from anaconda.org</span>
						<p><p>Running into issues downloading from anaconda.org where HTTP 500 errors are being thrown.</p>

<p>xref: https://github.com/Anaconda-Platform/support/issues/36</p>
</p>
						
							<p><em>Update 2016-09-21 19:39:11</em><br/>
							<p>Have not been seeing this in the days following. Closing under the assumption it is resolved.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-16 00:25:37 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">AppVeyor API error</span>
						<p><p>Getting HTTP 500 errors from AppVeyor when attempting to create feedstocks. This is blocking conversion.</p>

<p>xref: https://github.com/conda-forge/status/issues/7</p>
</p>
						
							<p><em>Update 2016-09-16 00:53:16</em><br/>
							<p>This issue is now resolved.</p>

							</p>
						
							<p><em>Update 2016-09-21 02:26:27</em><br/>
							<p>This is reoccurring.</p>

							</p>
						
							<p><em>Update 2016-09-23 16:06:13</em><br/>
							<p>Resolved since.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-13 00:43:13 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Travis CI Backlog</span>
						<p><p>Appears that Travis CI's workers are saturated and have been so most of the day. Builds proceeding slowly or taking awhile to start in the org.</p>

<p>xref: https://github.com/travis-ci/travis-ci/issues/6597</p>
</p>
						
							<p><em>Update 2016-09-21 19:35:58</em><br/>
							<p>This particular issue appears to have been cleared since.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-09 04:09:16 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">staged-recipes blocked (AppVeyor API error)</span>
						<p><p>Getting http 500 error from AppVeyor when attempting to create feedstocks. This is blocking conversion.</p>

<p>xref: https://github.com/conda-forge/status/issues/7</p>
</p>
						
							<p><em>Update 2016-09-11 20:12:56</em><br/>
							<p>Resolved since. Closing...</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-07 17:52:18 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Travis OS X Backlog</span>
						<p><p>Travis CI is experiencing a backlog that they are working through. Please see this <a href="https://www.traviscistatus.com/incidents/djchlfm22nl2 ">incident log</a> for more details.</p>
</p>
						
							<p><em>Update 2016-09-12 14:01:36</em><br/>
							<p>Closing as this appears to be resolved.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-09-01 02:56:06 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">staged-recipes blocked</span>
						<p><p>Staged-recipes is blocked because of an incompatibility between the new <code>conda-build</code> and <code>conda-smithy</code> as evidenced by <a href="https://travis-ci.org/conda-forge/staged-recipes#L153 ">build</a>. A working fix is proposed in PR ( https://github.com/conda-forge/staged-recipes/pull/1453 ). Merging it should fix the problem at present.</p>
</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-30 00:56:33 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Heighted error rate of API calls</span>
						<p><p>Travis CI has acknowledged they have a heightened rate of API call failures on their status page. Let's track the impact at conda-forge under this issue. The Travis CI incident report is linked below.</p>

<p>xref: https://www.traviscistatus.com/incidents/hgxqvblhj98z</p>
</p>
						
							<p><em>Update 2016-08-30 02:07:29</em><br/>
							<p>Appears to be resolved.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-28 01:21:18 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">AppVeyor</span>
						
						<hr/>

						<span class="title">AppVeyor builds missing (webhooks failing) </span>
						<p><p>Appears AppVeyor builds are not being triggered. Looking more closely it appears that the webhooks used to trigger builds are failing. This includes at <code>staged-recipes</code> and at the feedstocks. Raised an issue upstream ( https://github.com/appveyor/ci/issues/1002 ) to get more info and hopefully find a fix.</p>
</p>
						
							<p><em>Update 2016-08-28 01:51:17</em><br/>
							<p>This appears to not be happening now. Going to change to degraded performance until we know more.</p>

							</p>
						
							<p><em>Update 2016-09-09 03:14:02</em><br/>
							<p>Marking as resolved as we haven't seen this recently. Also upstream has done some maintenance recently to address this issue. Please let us know if you see a recurrence.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-24 19:16:13 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">CircleCI</span>
						
						<hr/>

						<span class="title">CircleCI login issues </span>
						<p><p>CircleCI has reported an increase in login issues. See this <a href="http://status.circleci.com/incidents/swr6g9rbjdbj ">announcement</a>. If this is affecting you, please let us know.</p>
</p>
						
							<p><em>Update 2016-08-25 03:10:36</em><br/>
							<p>Marked as resolved upstream. Marking as resolved here. If you do run into issues, please let us know and we can get in touch with upstream about it.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-24 04:46:57 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">AppVeyor API blocking conversion</span>
						<p><p>AppVeyor API registration error with <code>itsdangerous</code> is blocking feedstock conversion. Will also result in <code>itsdangerous</code> showing up in PRs. Users are recommended to merge with <code>master</code> and remove <code>itsdangerous</code> from their PRs. Snippet of the traceback shown below. Several restarts of the conversion step have been tried without success. </p>

<p><code>
CI Summary for conda-forge/itsdangerous-feedstock (can take ~30s):
 * conda-forge/itsdangerous-feedstock already enabled on travis-ci
 * conda-forge/itsdangerous-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 9, in &lt;module&gt;
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in &lt;module&gt;
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpw0ne44uj__feedstocks/itsdangerous-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
</code></p>

<p>cc @pelson</p>
</p>
						
							<p><em>Update 2016-08-24 05:01:50</em><br/>
							<p>After several restarts and a bit of time this resolved itself. However, this is hardly the first time I have seen this issue today or in general with AppVeyor's API. Maybe we need to use a similar strategy to one used with Travis CI's API.</p>

							</p>
						
							<p><em>Update 2016-09-03 03:47:25</em><br/>
							<p>Seeing a recurrence of this issue. See this <a href="https://travis-ci.org/conda-forge/staged-recipes/builds/157257319#L307 ">build</a> as an example.</p>

							</p>
						
							<p><em>Update 2016-09-03 03:52:28</em><br/>
							<p>In summary: AppVeyor are issuing a http 500 error intermittently when attempting to create a feedstock.</p>

<p>(For the status page, this is probably all that is needed, right @jakirkham?)</p>

							</p>
						
							<p><em>Update 2016-09-03 04:39:53</em><br/>
							<p>Yeah I'm still trying to find a healthy balance. In any event staged-recipes is cleared, so closing this out again.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-24 01:59:49 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">Travis CI</span>
						
						<hr/>

						<span class="title">Travis CI OS X Backlog</span>
						<p><p>Seems that there is some serious issue affecting Travis CI builds and causing them to wait for long periods on the queue. Have raised this issue upstream as ( https://github.com/travis-ci/travis-ci/issues/6515 ) to see if they have any ideas as to what is going on and if we can get it fixed.</p>

<p>For the meantime, I'd like to ask people to nice builds. If you see multiple builds for a PR at staged-recipes, please cancel all older version of it. If you are planning any large running builds, please hold off on them until we can track down this issue. It does seem some builds are getting processed, but it appears to be very slowly and long after they were initiated.</p>

<p>Please bear with us as we try to sort out this issue.</p>
</p>
						
							<p><em>Update 2016-08-24 03:12:44</em><br/>
							<p>Reducing to degraded as we seem to actually have some things running on the queue now. Also looks like the number of jobs running is starting to fall off. Will continue to monitor the situation.</p>

							</p>
						
							<p><em>Update 2016-08-24 18:47:04</em><br/>
							<p>Travis CI has now <a href="https://www.traviscistatus.com/incidents/4mvp857qx8bw ">announced</a> that they are stopping all OS X builds due to instability in their OS X infrastructure. Upgrading this to major outage.</p>

							</p>
						
							<p><em>Update 2016-08-25 03:12:53</em><br/>
							<p>Adding staged-recipes to this outage as conversions to feedstocks occur on Travis CI. So they will similarly be blocked until Travis CI comes back online.</p>

							</p>
						
							<p><em>Update 2016-08-25 18:58:09</em><br/>
							<p>It appears Travis CI is re-enabling OS X builds and are starting to work through the backlog. Downgrading to degraded performance. Will provide more updates as this progresses.</p>

							</p>
						
							<p><em>Update 2016-08-26 05:59:34</em><br/>
							<p>Have removed staged-recipes as they have cleared. Feel free to close this when you are comfortable with Travis CI's progress.</p>

							</p>
						
							<p><em>Update 2016-08-27 15:16:39</em><br/>
							<p>This seems to be resolved now. Going to go ahead and close this out. If people are still having issues, please let us know.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-19 22:40:35 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">AppVeyor</span>
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">staged-recipes blocked up</span>
						<p><p>There are a couple of recipes that are still stuck in staged-recipes. Restarting the <a href="https://travis-ci.org/conda-forge/staged-recipes/jobs/153672103#L391 ">build</a> failed. Snippet of the traceback shown below.</p>

<p><code>
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in &lt;module&gt;
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in &lt;module&gt;
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp5236hjzg__feedstocks/eventlet-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
</code></p>

<p>It is possible this was in part a consequence of trying to handle recipes that were already converted. Alternatively this could be caused by some issues with AppVeyor's API.</p>
</p>
						
							<p><em>Update 2016-08-19 22:41:57</em><br/>
							<p>A new <a href="https://travis-ci.org/conda-forge/staged-recipes/builds/153689664 ">build</a> was created with the merge of PR ( https://github.com/conda-forge/staged-recipes/pull/1312 ) that does not have any of the converted feedstocks in it to finish the conversion. Will wait and see how that build progresses.</p>

							</p>
						
							<p><em>Update 2016-08-19 22:45:31</em><br/>
							<p>This appears to have resolved this issue. staged-recipes is now clear.</p>

							</p>
						
							<p><em>Update 2016-08-20 21:34:08</em><br/>
							<p>Running into this issue again. So am reopening. See this <a href="https://travis-ci.org/conda-forge/staged-recipes/jobs/153845433 ">build</a>. Traceback included below. Have tried restarting once, but it failed. Will try again.</p>

<p><code>
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 9, in &lt;module&gt;
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in &lt;module&gt;
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpu35f06wx__feedstocks/argparse-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
</code></p>

<p>cc @msarahan</p>

							</p>
						
							<p><em>Update 2016-08-20 21:45:27</em><br/>
							<p>Tried to add PR ( https://github.com/conda-forge/staged-recipes/pull/1317 ) to ensure we were using the latest set of recipes at staged-recipes. It seems Travis CI likes to checkout commits now and so can sometimes be out-of-date. Doesn't appear this made any difference. See this <a href="https://travis-ci.org/conda-forge/staged-recipes/jobs/153849261 ">build</a>, which has the same failure.</p>

							</p>
						
							<p><em>Update 2016-08-20 21:49:37</em><br/>
							<p>Attempting to temporarily remove <code>argparse</code> as it is having trouble getting converted ATM. Will try to re-add afterwards. See PR ( https://github.com/conda-forge/staged-recipes/pull/1318 ) for this temporary removal.</p>

							</p>
						
							<p><em>Update 2016-08-20 21:56:08</em><br/>
							<p>Removing <code>argparse</code> made no difference as the next recipe in the list has the same <a href="https://travis-ci.org/conda-forge/staged-recipes/jobs/153850184 ">problem</a>. Went ahead and re-added <code>argparse</code> with PR ( https://github.com/conda-forge/staged-recipes/pull/1319 ).</p>

							</p>
						
							<p><em>Update 2016-08-20 22:01:21</em><br/>
							<p>Weird. Apparently after re-adding <code>argparse</code> we were able to get everything working again. All of the recipes are now converted.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-18 23:43:30 UTC</span>

						
							<span class="label degraded performance float-right">degraded performance</span>
						
						
							<span class="label system float-right">Anaconda.org</span>
						
						<hr/>

						<span class="title">Issues uploading to Anaconda</span>
						<p><p>It appears there are some issues uploading to Anaconda.org on all CIs. Here is a <a href="https://ci.appveyor.com/project/conda-forge/hdbscan-feedstock/build/1.0.10/job/ljwl03dcll9xitqy#L449 ">log</a> from one such failed AppVeyor upload failure. Though similar ones can be seen for all CIs. Snippet of traceback shown below. Restarting seems to sometimes fix it.</p>

<p><code>
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in &lt;module&gt;
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "C:\conda\lib\site-packages\binstar_client\__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -&gt; 404)', 404)
Command exited with code 1
</code></p>

<p>cc @msarahan @mcg1969</p>
</p>
						
							<p><em>Update 2016-08-18 23:50:23</em><br/>
							<p>Raising for awareness of affected teams/feedstocks that have tried to deploy recently and are now having deployment issues. Feel free to track an issue locally on your feedstock until all missing packages are uploaded.</p>

<p>cc @conda-forge/bqplot @conda-forge/requests-futures @conda-forge/hdbscan @conda-forge/versioneer</p>

							</p>
						
							<p><em>Update 2016-08-18 23:58:53</em><br/>
							<p>Restarted builds for the apparently affected feedstocks. Seems to be localized to very recent updates or new feedstocks.</p>

							</p>
						
							<p><em>Update 2016-08-19 00:32:22</em><br/>
							<p>All of the restarted builds appear to have passed and uploaded packages FWICT. If others can confirm, that would be great. Going to go ahead and close for now assuming this is resolved.</p>

							</p>
						
							<p><em>Update 2016-08-19 05:10:29</em><br/>
							<p>Yeah, was just noticing this with a different CircleCI <a href="https://circleci.com/gh/conda-forge/statuspage-feedstock/12 ">build</a> just now. That build was from a few days ago. Going to elevate this issue.</p>

							</p>
						
							<p><em>Update 2016-08-19 05:15:07</em><br/>
							<p>Raised issue ( https://github.com/Anaconda-Platform/support/issues/60 ) about this general problem.</p>

							</p>
						
							<p><em>Update 2016-08-19 12:55:05</em><br/>
							<p>Try restarting the build and see if it fixes it. This has also worked for me with CircleCI builds that failed to upload.</p>

							</p>
						
							<p><em>Update 2016-08-19 15:06:27</em><br/>
							<p>In some cases, am also seeing a new failure when rerunning an existing build that had already uploaded. This rerunning is being done in order to resolve some of the failed uploads. This new failure suggests the problem is not strictly limited to uploading. See the traceback below for the error and this <a href="https://ci.appveyor.com/project/conda-forge/astroid-feedstock/build/1.0.2/job/h126inb8iwx02cnx#L754 ">build</a> for more details.</p>

<p><code>
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in &lt;module&gt;
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 28, in show_channel
    res = self.session.get(url)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 628, in send
    r.content
  File "C:\conda\lib\site-packages\requests\models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\conda\lib\site-packages\requests\models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Command exited with code 1
</code></p>

							</p>
						
							<p><em>Update 2016-08-19 15:30:51</em><br/>
							<p>Appears your feedstock was affected as well, @conda-forge/cssutils. Have restarted the CircleCI build.</p>

							</p>
						
							<p><em>Update 2016-08-21 17:14:56</em><br/>
							<p>Was starting to look like things were stabilizing as I hadn't seen this issue for awhile. However, saw this <a href="https://ci.appveyor.com/project/conda-forge/gdal-feedstock/build/1.0.226/job/evs1m32fyd71wjwl#L4941 ">build</a> from <code>gdal</code> that is struggling with a related problem.</p>

<p>Edit: Restarted the build.</p>

<p>cc @conda-forge/gdal</p>

							</p>
						
							<p><em>Update 2016-08-21 17:17:22</em><br/>
							<p>Also happened with some <code>curl</code> <a href="https://ci.appveyor.com/project/conda-forge/curl-feedstock/build/1.0.20 ">builds</a> recently.</p>

<p>Edit: Restarted those too.</p>

<p>cc @conda-forge/curl</p>

							</p>
						
							<p><em>Update 2016-08-21 17:19:35</em><br/>
							<p>Appears <code>pysocks</code> suffered from this in yesterday's <a href="https://ci.appveyor.com/project/conda-forge/pysocks-feedstock/build/1.0.1 ">builds</a>. Have restarted them.</p>

<p>cc @conda-forge/pysocks</p>

							</p>
						
							<p><em>Update 2016-08-21 17:22:10</em><br/>
							<p>Affecting <code>sphinx</code> on both <a href="https://circleci.com/gh/conda-forge/sphinx-feedstock/7 ">CircleCI</a> and <a href="https://ci.appveyor.com/project/conda-forge/sphinx-feedstock/build/1.0.7 ">AppVeyor</a>. Have restarted both.</p>

<p>cc @conda-forge/sphinx</p>

							</p>
						
							<p><em>Update 2016-08-21 20:42:14</em><br/>
							<p>Can confirm this is happening with all CIs now thanks to being able to track down this issue with Travis CI. ( https://github.com/conda-forge/line_profiler-feedstock/issues/6 ) Have already triggered a rebuild to get the missing packages.</p>

<p>cc @conda-forge/line_profiler</p>

							</p>
						
							<p><em>Update 2016-08-24 18:59:26</em><br/>
							<p>It looks like we may need some improvements to how we are doing uploads. This is documented briefly in issue ( https://github.com/conda-forge/conda-smithy/issues/270 ). It relies on a new Anaconda API that is going through some testing before it rolls out in the next day or two.</p>

							</p>
						
							<p><em>Update 2016-08-28 00:00:27</em><br/>
							<p>Turns out this issue goes back several weeks as demonstrated by this <a href="https://circleci.com/gh/conda-forge/pyflakes-feedstock/3 ">failure</a>.</p>

							</p>
						
							<p><em>Update 2016-08-28 00:22:33</em><br/>
							<p>FWIW I haven't seen this issue really at all today. So maybe things are already improving.</p>

							</p>
						
							<p><em>Update 2016-08-28 16:44:41</em><br/>
							<p>This is still persisting. Here is a recent <a href="https://circleci.com/gh/conda-forge/yarg-feedstock/1 ">failure</a>.</p>

							</p>
						
							<p><em>Update 2016-09-21 19:39:45</em><br/>
							<p>Seeing an uptick in this issue of late.</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-18 19:26:48 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">Conversion failure</span>
						<p><p>Appears there is some issue be encountered during conversion. May be related to the recent <code>conda-build</code> upgrade.</p>

<p>Traceback shown below. See this <a href="https://travis-ci.org/conda-forge/staged-recipes/jobs/153361154 ">log</a> for more details.</p>

<p><code>
Calculating the recipes which need to be turned into feedstocks.
Making feedstock for versioneer
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in &lt;module&gt;
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 103, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 34, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 361, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 24, in render_run_docker_build
    with fudge_subdir('linux-64'):
  File "/Users/travis/miniconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 103, in fudge_subdir
    orig = conda_build.metadata.cc.subdir
AttributeError: module 'conda_build.metadata' has no attribute 'cc'
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 150, in &lt;module&gt;
    '--feedstock-directory', feedstock_dir])
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'init', '/Users/travis/build/conda-forge/staged-recipes/recipes/versioneer', '--feedstock-directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpx54jano2__feedstocks/versioneer-feedstock']' returned non-zero exit status 1
</code></p>

<p>cc @patricksnape @msarahan @pelson</p>
</p>
						
							<p><em>Update 2016-08-18 19:28:42</em><br/>
							<p>Happened in the subsequent <a href="https://travis-ci.org/conda-forge/staged-recipes/builds/153362768 ">build</a> too. May be worthwhile to pin <code>conda-build</code> to the last known working version (<code>1.21.11</code>) in the feedstock conversion script for now. Not sure if this is also related to <code>conda-build-all</code> or <code>conda-smithy</code>.</p>

							</p>
						
							<p><em>Update 2016-08-18 19:33:27</em><br/>
							<p>Adding PR ( https://github.com/conda-forge/staged-recipes/pull/1293 ) to workaround this issue for the meantime.</p>

							</p>
						
							<p><em>Update 2016-08-18 19:54:51</em><br/>
							<p>Resolved via pinning of <code>conda-build</code> to version <code>1.21.11</code> for feedstock conversion via PR ( https://github.com/conda-forge/staged-recipes/pull/1293 ).</p>

							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-14 19:43:20 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">docs</span>
						
						<hr/>

						<span class="title">Testing...</span>
						<p><p>Just testing please ignore and unsubscribe.</p>
</p>
						
							<p><em>Update 2016-08-14 19:43:48</em><br/>
							<p>Testing completed.</p>

							</p>
						
							<p><em>Update 2016-08-17 14:54:05</em><br/>
							<p>Reopening for testing.</p>

							</p>
						
					</div>
					
				
			</section>


			<footer class="footer">
				<section class="container">
					<hr/>
					
					<p>Status page hosted by GitHub, generated with <a href="https://github.com/pyupio/statuspage">pyupio/statuspage</a></p>
				</section>
			</footer>

		</main>

	</body>
</html>